In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append("..")

In [3]:
from optimus import Optimus

In [36]:
op = Optimus("polars")

In [37]:
df = op.load.parquet("../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet")

cccc naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
vvvv (<polars.internals.lazy_frame.LazyFrame object at 0x0000018649E5F910>,)
dddd naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None

In [92]:
for i in df.data.fetch(10).dtypes:
    print(i.__name__.lower())

int64
int64
int64
int64
utf8
utf8
utf8
int64
utf8
utf8
utf8
utf8
utf8
utf8
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
utf8
utf8
utf8
utf8
utf8
utf8
utf8
utf8
utf8
utf8
utf8
utf8
utf8
utf8

In [65]:
for i in df.data.collect().dtypes:
    print(dir(i))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']

In [95]:
%%time
df.cols.data_type()

naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
Wall time: 400 ms

{'NO': 'int64',
 'CO_ID': 'int64',
 'ARPU': 'int64',
 'TENURE': 'int64',
 'FECHA_INST_TELEFONO': 'utf8',
 'FECHA_INSTALACION': 'utf8',
 'STATUS_TELEFONO': 'utf8',
 'CANAL_VENTA': 'int64',
 'SUB_CANAL_VENTA': 'utf8',
 'ID_VENDEDOR': 'utf8',
 'ID_PLAN': 'utf8',
 'PLAN_PREPAGO': 'utf8',
 'ID_PLAN_ANTERIOR': 'utf8',
 'FECHA_CAMBIO_PLAN': 'utf8',
 'TRA_IN_LOC_Mean_6_MESES': 'float64',
 'TRA_IN_INT_Mean_6_MESES': 'float64',
 'TRA_IN_NAT_Mean_6_MESES': 'float64',
 'TRA_IN_MOBILE_Mean_6_MESES': 'float64',
 'TRA_IN_MOBILE_OTHER_Mean_6_MESES': 'float64',
 'TRA_OUT_LOC_Mean_6_MESES': 'float64',
 'TRA_OUT_INT_Mean_6_MESES': 'float64',
 'TRA_OUT_NAT_Mean_6_MESES': 'float64',
 'TRA_OUT_MOBILE_Mean_6_MESES': 'float64',
 'TRA_OUT_MOBILE_OTHER_Mean_6_MESES': 'float64',
 'SMS_OUT_AMT_Mean_6_MESES': 'float64',
 'RECHARGE_AMT_Mean_6_MESES': 'float64',
 'AMT_RENT_Mean_6_MESES': 'float64',
 'AMT_MIN_OUT_INT_Mean_6_MESES': 'float64',
 'AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES': 'float64',
 'AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES': 'float64',
 'AMT_MIN_OUT_MOBILE_Mean_6_MESES': 'float64',
 'AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES': 'float64',
 'AMT_ROAMING_SMS_Mean_6_MESES': 'float64',
 'AMT_ROAMING_DATA_Mean_6_MESES': 'float64',
 'AMT_ROAMING_VOICE_Mean_6_MESES': 'float64',
 'AMT_PAQUETICO_VOZ_Mean_6_MESES': 'float64',
 'AMT_PAQUETICO_DATA_Mean_6_MESES': 'float64',
 'AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES': 'float64',
 'MB_Mean_6_MESES': 'float64',
 'TRA_IN_LOC_Mean_3_MESES': 'float64',
 'TRA_IN_INT_Mean_3_MESES': 'float64',
 'TRA_IN_NAT_Mean_3_MESES': 'float64',
 'TRA_IN_MOBILE_Mean_3_MESES': 'float64',
 'TRA_IN_MOBILE_OTHER_Mean_3_MESES': 'float64',
 'TRA_OUT_LOC_Mean_3_MESES': 'float64',
 'TRA_OUT_INT_Mean_3_MESES': 'float64',
 'TRA_OUT_NAT_Mean_3_MESES': 'float64',
 'TRA_OUT_MOBILE_Mean_3_MESES': 'float64',
 'TRA_OUT_MOBILE_OTHER_Mean_3_MESES': 'float64',
 'SMS_OUT_AMT_Mean_3_MESES': 'float64',
 'RECHARGE_AMT_Mean_3_MESES': 'float64',
 'AMT_RENT_Mean_3_MESES': 'float64',
 'AMT_MIN_OUT_INT_Mean_3_MESES': 'float64',
 'AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES': 'float64',
 'AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES': 'float64',
 'AMT_MIN_OUT_MOBILE_Mean_3_MESES': 'float64',
 'AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES': 'float64',
 'AMT_ROAMING_SMS_Mean_3_MESES': 'float64',
 'AMT_ROAMING_DATA_Mean_3_MESES': 'float64',
 'AMT_ROAMING_VOICE_Mean_3_MESES': 'float64',
 'AMT_PAQUETICO_VOZ_Mean_3_MESES': 'float64',
 'AMT_PAQUETICO_DATA_Mean_3_MESES': 'float64',
 'AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES': 'float64',
 'MB_Mean_3_MESES': 'float64',
 'FECHA_NACIMIENTO': 'utf8',
 'SEXO': 'utf8',
 'SEGMENTO_BI': 'utf8',
 'DESCRIPCION_PROVINCIA_CUENTA': 'utf8',
 'DESCRIPCION_PROVINCIA_CVOZ': 'utf8',
 'DESCRIPCION_PROVINCIA_CDATA': 'utf8',
 'PROVINCIA': 'utf8',
 'MONTO_RECARGA_Sum_MES_ANTERIOR': 'utf8',
 'CANT_RECARGAS_MES_ANTERIOR': 'utf8',
 'CABLE': 'utf8',
 'TELEFONO_FIJO': 'utf8',
 'INTERNET': 'utf8',
 'MBB': 'utf8',
 'MOVIL_POSPAGO': 'utf8'}

In [96]:
type(df.data)

polars.internals.lazy_frame.LazyFrame

In [100]:
df.rows.limit()

naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10]
SLICE[offset: 0, len: 11] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10]
SLICE[offset: 0, len: 11] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10]
SLICE[offset: 0, len: 11] sdf
ASADASDASD naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10]
SLICE[offset: 0, len: 11]
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
ttttt <class 'polars.internals.lazy_frame.LazyFrame'>
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
mmmmmmmmm naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10]
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
SLICE[offset: 0, len: 10] sdf

ASADASDASD shape: (10, 78)
┌─────┬───────────┬──────┬────────┬─────┬───────────────┬──────────┬────────┬───────────────┐
│ NO  ┆ CO_ID     ┆ ARPU ┆ TENURE ┆ ... ┆ TELEFONO_FIJO ┆ INTERNET ┆ MBB    ┆ MOVIL_POSPAGO │
│ --- ┆ ---       ┆ ---  ┆ ---    ┆     ┆ ---           ┆ ---      ┆ ---    ┆ ---           │
│ i64 ┆ i64       ┆ i64  ┆ i64    ┆     ┆ str           ┆ str      ┆ str    ┆ str           │
╞═════╪═══════════╪══════╪════════╪═════╪═══════════════╪══════════╪════════╪═══════════════╡
│ 1   ┆ 12881892  ┆ 384  ┆ 109    ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 136449998 ┆ 410  ┆ 32     ┆ ... ┆ $null$        ┆ $null$   ┆ 1      ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 15661796  ┆ 654  ┆ 93     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 127068927 ┆ 350  ┆ 37     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ... ┆ ...       ┆ ...  ┆ ...    ┆ ... ┆ ...           ┆ ...      ┆ ...    ┆ ...           │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7   ┆ 73882646  ┆ 596  ┆ 59     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 8   ┆ 3385917   ┆ 288  ┆ 181    ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 9   ┆ 116622990 ┆ 713  ┆ 44     ┆ ... ┆ $null$        ┆ $null$   ┆ 1      ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10  ┆ 81969494  ┆ 702  ┆ 57     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
└─────┴───────────┴──────┴────────┴─────┴───────────────┴──────────┴────────┴───────────────┘

AttributeError: collect

       NO      CO_ID       ARPU     TENURE  FECHA_INST_TELEFONO    FECHA_INSTALACION    STATUS_TELEFONO      CANAL_VENTA    SUB_CANAL_VENTA  ID_VENDEDOR    ID_PLAN     PLAN_PREPAGO    ID_PLAN_ANTERIOR    FECHA_CAMBIO_PLAN      TRA_IN_LOC_Mean_6_MESES    TRA_IN_INT_Mean_6_MESES    TRA_IN_NAT_Mean_6_MESES    TRA_IN_MOBILE_Mean_6_MESES    TRA_IN_MOBILE_OTHER_Mean_6_MESES    TRA_OUT_LOC_Mean_6_MESES    TRA_OUT_INT_Mean_6_MESES    TRA_OUT_NAT_Mean_6_MESES    TRA_OUT_MOBILE_Mean_6_MESES    TRA_OUT_MOBILE_OTHER_Mean_6_MESES    SMS_OUT_AMT_Mean_6_MESES    RECHARGE_AMT_Mean_6_MESES    AMT_RENT_Mean_6_MESES    AMT_MIN_OUT_INT_Mean_6_MESES    AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES    AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES    AMT_MIN_OUT_MOBILE_Mean_6_MESES    AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES    AMT_ROAMING_SMS_Mean_6_MESES    AMT_ROAMING_DATA_Mean_6_MESES    AMT_ROAMING_VOICE_Mean_6_MESES    AMT_PAQUETICO_VOZ_Mean_6_MESES    AMT_PAQUETICO_DATA_Mean_6_MESES    AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES    MB_Mean_6_MESES    TRA_IN_LOC_Mean_3_MESES    TRA_IN_INT_Mean_3_MESES    TRA_IN_NAT_Mean_3_MESES    TRA_IN_MOBILE_Mean_3_MESES    TRA_IN_MOBILE_OTHER_Mean_3_MESES    TRA_OUT_LOC_Mean_3_MESES    TRA_OUT_INT_Mean_3_MESES    TRA_OUT_NAT_Mean_3_MESES    TRA_OUT_MOBILE_Mean_3_MESES    TRA_OUT_MOBILE_OTHER_Mean_3_MESES    SMS_OUT_AMT_Mean_3_MESES    RECHARGE_AMT_Mean_3_MESES    AMT_RENT_Mean_3_MESES    AMT_MIN_OUT_INT_Mean_3_MESES    AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES    AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES    AMT_MIN_OUT_MOBILE_Mean_3_MESES    AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES    AMT_ROAMING_SMS_Mean_3_MESES    AMT_ROAMING_DATA_Mean_3_MESES    AMT_ROAMING_VOICE_Mean_3_MESES    AMT_PAQUETICO_VOZ_Mean_3_MESES    AMT_PAQUETICO_DATA_Mean_3_MESES    AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES    MB_Mean_3_MESES  FECHA_NACIMIENTO     SEXO      SEGMENTO_BI    DESCRIPCION_PROVINCIA_CUENTA    DESCRIPCION_PROVINCIA_CVOZ    DESCRIPCION_PROVINCIA_CDATA    PROVINCIA             MONTO_RECARGA_Sum_MES_ANTERIOR    CANT_RECARGAS_MES_ANTERIOR    CABLE     TELEFONO_FIJO    INTERNET    MBB       MOVIL_POSPAGO
  (int64)    (int64)    (int64)    (int64)  (utf8)                 (utf8)               (utf8)                   (int64)             (utf8)  (utf8)         (utf8)      (utf8)          (utf8)              (utf8)                               (float64)                  (float64)                  (float64)                     (float64)                           (float64)                   (float64)                   (float64)                   (float64)                      (float64)                            (float64)                   (float64)                    (float64)                (float64)                       (float64)                                (float64)                               (float64)                          (float64)                                     (float64)                       (float64)                        (float64)                         (float64)                         (float64)                          (float64)                              (float64)          (float64)                  (float64)                  (float64)                  (float64)                     (float64)                           (float64)                   (float64)                   (float64)                   (float64)                      (float64)                            (float64)                   (float64)                    (float64)                (float64)                       (float64)                                (float64)                               (float64)                          (float64)                                     (float64)                       (float64)                        (float64)                         (float64)                         (float64)                          (float64)                              (float64)          (float64)  (utf8)               (utf8)    (utf8)         (utf8)                          (utf8)                        (utf8)                         (utf8)                (utf8)                            (utf8)                        (utf8)    (utf8)           (utf8)      (utf8)    (utf8)
---------  ---------  ---------  ---------  ---------------------  -------------------  -----------------  -------------  -----------------  -------------  ----------  --------------  ------------------  -------------------  -------------------------  -------------------------  -------------------------  ----------------------------  ----------------------------------  --------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------------  --------------------------  ---------------------------  -----------------------  ------------------------------  ---------------------------------------  --------------------------------------  ---------------------------------  --------------------------------------------  ------------------------------  -------------------------------  --------------------------------  --------------------------------  ---------------------------------  -------------------------------------  -----------------  -------------------------  -------------------------  -------------------------  ----------------------------  ----------------------------------  --------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------------  --------------------------  ---------------------------  -----------------------  ------------------------------  ---------------------------------------  --------------------------------------  ---------------------------------  --------------------------------------------  ------------------------------  -------------------------------  --------------------------------  --------------------------------  ---------------------------------  -------------------------------------  -----------------  -------------------  --------  -------------  ------------------------------  ----------------------------  -----------------------------  --------------------  --------------------------------  ----------------------------  --------  ---------------  ----------  --------  ---------------
        1   12881892        384        109  2013-01-30 00:00:00    2013-01-30 00:00:00  A                              6               4601  18425          CEPREVO005  S               $null$              $null$                                   1.55                       0.986                      2.384                        17.903                              35.277                       4.271                       0                           2.16                           6.134                                7.396                       3.143                      340.651                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0.014                      1.763                      1.32                       3.703                        17.527                              39.467                       2.58                        0                            0.76                          8                                    5.837                       5.333                      282.047                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0.011  1982-04-12 00:00:00  M         E              SAN PEDRO DE MACORIS            SAN PEDRO DE MACORIS          $null$                         SAN PEDRO DE MACORIS  76.920                            1                             1         $null$           $null$      $null$    $null$
        2  136449998        410         32  2019-07-19 00:00:00    2022-02-06 00:00:00  A                              3               2903  24425          CEPREVO004  S               $null$              $null$                                   3.323                      0                          0                           126.01                                5.379                       0.007                       0                           0                             18.44                                 1.474                       4                          393.626                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           3505.54                       2.173                      0                          0                           128.703                               4.597                       0.017                       0                            0                             0.753                                0.1                         5.333                      197.433                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           2940.91   1995-05-10 00:00:00  F         $null$         DUARTE                          DUARTE                        $null$                         DUARTE                $null$                            $null$                        $null$    $null$           $null$      1         $null$
        3   15661796        654         93  2014-06-20 00:00:00    2014-06-20 00:00:00  A                              6                358  19394          CEPREVO005  S               $null$              $null$                                   0.124                      0                          0                           110.039                              87.179                       0.549                       0                           0                              9.119                                5.939                      16.143                      515.26                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          20121.6                        0.29                       0                          0                           112.61                               19.15                        0                           0                            0                            12.01                                 9.71                       14.333                      575.98                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          23524.5    1993-02-15 00:00:00  F         E              DISTRITO NACIONAL               SAN JUAN                      $null$                         SAN JUAN              804.880                           8                             $null$    $null$           $null$      $null$    $null$
        4  127068927        350         37  2019-01-29 00:00:00    2019-01-31 00:00:00  A                              3               1919  23502          CEPREVO005  S               $null$              $null$                                   0.566                      0                          0                             3.311                               3.483                       0                           0                           0                              0.069                                0.471                       0                          212.297                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           1296.56                       0                          0                          0                             0.493                               5.147                       0                           0                            0                             0.16                                 1.1                         0                           38.46                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              1.238  1973-09-30 00:00:00  F         E              AZUA                            SANTIAGO                      $null$                         SANTIAGO              115.380                           2                             $null$    $null$           $null$      $null$    $null$
        5  156732494        660          9  2021-06-14 00:00:00    2021-06-14 00:00:00  A                              6              11361  E6314          CEPREVO005  S               $null$              $null$                                   0.049                      0                          0                             1.137                              10.38                        0.263                       0                           0                              1.071                                4.966                       2                          348.34                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          11663.5                        0                          0                          0                             0.653                               0.433                       0.613                       0                            0                             1.12                                 2.133                       2.667                      307.68                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          11349.3    1997-07-30 00:00:00  F         E              DISTRITO NACIONAL               SANTO DOMINGO                 $null$                         SANTO DOMINGO         $null$                            $null$                        $null$    $null$           $null$      $null$    $null$
        6  158282264        741          7  2021-07-30 00:00:00    2021-07-30 00:00:00  A                              3               5598  25430          CEPREVO005  S               $null$              $null$                                   0                          0                          0                             0.3                                 3.246                       0                           0                           0                              1.094                                5.943                       1.857                       63.954                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0            164.832                      0                          0                          0                             0                                   0.713                       0                           0                            0                             0                                    0                           2.333                        0                            0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0      1990-12-24 00:00:00  M         E              BAHORUCO                        $null$                        $null$                         BAHORUCO              $null$                            $null$                        $null$    $null$           $null$      $null$    $null$

In [44]:
df.data.head(10).collect()

shape: (10, 78)
┌─────┬───────────┬──────┬────────┬─────┬───────────────┬──────────┬────────┬───────────────┐
│ NO  ┆ CO_ID     ┆ ARPU ┆ TENURE ┆ ... ┆ TELEFONO_FIJO ┆ INTERNET ┆ MBB    ┆ MOVIL_POSPAGO │
│ --- ┆ ---       ┆ ---  ┆ ---    ┆     ┆ ---           ┆ ---      ┆ ---    ┆ ---           │
│ i64 ┆ i64       ┆ i64  ┆ i64    ┆     ┆ str           ┆ str      ┆ str    ┆ str           │
╞═════╪═══════════╪══════╪════════╪═════╪═══════════════╪══════════╪════════╪═══════════════╡
│ 1   ┆ 12881892  ┆ 384  ┆ 109    ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 136449998 ┆ 410  ┆ 32     ┆ ... ┆ $null$        ┆ $null$   ┆ 1      ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 15661796  ┆ 654  ┆ 93     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 127068927 ┆ 350  ┆ 37     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ... ┆ ...       ┆ ...  ┆ ...    ┆ ... ┆ ...           ┆ ...      ┆ ...    ┆ ...           │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7   ┆ 73882646  ┆ 596  ┆ 59     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 8   ┆ 3385917   ┆ 288  ┆ 181    ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 9   ┆ 116622990 ┆ 713  ┆ 44     ┆ ... ┆ $null$        ┆ $null$   ┆ 1      ┆ $null$        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10  ┆ 81969494  ┆ 702  ┆ 57     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
└─────┴───────────┴──────┴────────┴─────┴───────────────┴──────────┴────────┴───────────────┘

In [29]:
df.table()

naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
aaaa <class 'polars.internals.lazy_frame.LazyFrame'>
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
aaaa <class 'polars.internals.lazy_frame.LazyFrame'>
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
aaaa <class 'polars.internals.lazy_frame.LazyFrame'>
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
aaaa <class 'polars.internals.lazy_frame.LazyFrame'>
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
aaaa <class 'polars.internals.lazy_frame.LazyFrame'>
-----bbbbbcc naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None <optimus.engines.polars.engine.PolarsEngine object at 0x0000020371DC20A0> None sass
====================
mmmmmmmmm naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
aaaa <class 'polars.internals.lazy_frame.LazyFrame'>
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
aaaa <class 'polars.internals.lazy_frame.LazyFrame'>
naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM
PARQUET SCAN ../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet; PROJECT */78 COLUMNS; SELECTION: None sdf
aaaa <class 'polars.internals.lazy_frame.LazyFrame'>
-----bbbbbcc naive plan: (run LazyFrame.describe_optimized_plan() to see the optimized plan)

SELECT 78 COLUMNS: [col("NO"), col("CO_ID"), col("ARPU"), col("TENURE"), col("FECHA_INST_TELEFONO"), col("FECHA_INSTALACION"), col("STATUS_TELEFONO"), col("CANAL_VENTA"), col("SUB_CANAL_VENTA"), col("ID_VENDEDOR"), col("ID_PLAN"), col("PLAN_PREPAGO"), col("ID_PLAN_ANTERIOR"), col("FECHA_CAMBIO_PLAN"), col("TRA_IN_LOC_Mean_6_MESES"), col("TRA_IN_INT_Mean_6_MESES"), col("TRA_IN_NAT_Mean_6_MESES"), col("TRA_IN_MOBILE_Mean_6_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_6_MESES"), col("TRA_OUT_LOC_Mean_6_MESES"), col("TRA_OUT_INT_Mean_6_MESES"), col("TRA_OUT_NAT_Mean_6_MESES"), col("TRA_OUT_MOBILE_Mean_6_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_6_MESES"), col("SMS_OUT_AMT_Mean_6_MESES"), col("RECHARGE_AMT_Mean_6_MESES"), col("AMT_RENT_Mean_6_MESES"), col("AMT_MIN_OUT_INT_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_6_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES"), col("AMT_ROAMING_SMS_Mean_6_MESES"), col("AMT_ROAMING_DATA_Mean_6_MESES"), col("AMT_ROAMING_VOICE_Mean_6_MESES"), col("AMT_PAQUETICO_VOZ_Mean_6_MESES"), col("AMT_PAQUETICO_DATA_Mean_6_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES"), col("MB_Mean_6_MESES"), col("TRA_IN_LOC_Mean_3_MESES"), col("TRA_IN_INT_Mean_3_MESES"), col("TRA_IN_NAT_Mean_3_MESES"), col("TRA_IN_MOBILE_Mean_3_MESES"), col("TRA_IN_MOBILE_OTHER_Mean_3_MESES"), col("TRA_OUT_LOC_Mean_3_MESES"), col("TRA_OUT_INT_Mean_3_MESES"), col("TRA_OUT_NAT_Mean_3_MESES"), col("TRA_OUT_MOBILE_Mean_3_MESES"), col("TRA_OUT_MOBILE_OTHER_Mean_3_MESES"), col("SMS_OUT_AMT_Mean_3_MESES"), col("RECHARGE_AMT_Mean_3_MESES"), col("AMT_RENT_Mean_3_MESES"), col("AMT_MIN_OUT_INT_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES"), col("AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_Mean_3_MESES"), col("AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES"), col("AMT_ROAMING_SMS_Mean_3_MESES"), col("AMT_ROAMING_DATA_Mean_3_MESES"), col("AMT_ROAMING_VOICE_Mean_3_MESES"), col("AMT_PAQUETICO_VOZ_Mean_3_MESES"), col("AMT_PAQUETICO_DATA_Mean_3_MESES"), col("AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES"), col("MB_Mean_3_MESES"), col("FECHA_NACIMIENTO"), col("SEXO"), col("SEGMENTO_BI"), col("DESCRIPCION_PROVINCIA_CUENTA"), col("DESCRIPCION_PROVINCIA_CVOZ"), col("DESCRIPCION_PROVINCIA_CDATA"), col("PROVINCIA"), col("MONTO_RECARGA_Sum_MES_ANTERIOR"), col("CANT_RECARGAS_MES_ANTERIOR"), col("CABLE"), col("TELEFONO_FIJO"), col("INTERNET"), col("MBB"), col("MOVIL_POSPAGO")]
FROM

TypeError: 'LazyFrame' object is not subscriptable

In [ ]:
df.rows.limit(10 + 1).cols.select()

In [58]:
df

shape: (163820, 78)
┌────────┬───────────┬──────┬────────┬─────┬───────────────┬──────────┬────────┬───────────────┐
│ NO     ┆ CO_ID     ┆ ARPU ┆ TENURE ┆ ... ┆ TELEFONO_FIJO ┆ INTERNET ┆ MBB    ┆ MOVIL_POSPAGO │
│ ---    ┆ ---       ┆ ---  ┆ ---    ┆     ┆ ---           ┆ ---      ┆ ---    ┆ ---           │
│ i64    ┆ i64       ┆ i64  ┆ i64    ┆     ┆ str           ┆ str      ┆ str    ┆ str           │
╞════════╪═══════════╪══════╪════════╪═════╪═══════════════╪══════════╪════════╪═══════════════╡
│ 1      ┆ 12881892  ┆ 384  ┆ 109    ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2      ┆ 136449998 ┆ 410  ┆ 32     ┆ ... ┆ $null$        ┆ $null$   ┆ 1      ┆ $null$        │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3      ┆ 15661796  ┆ 654  ┆ 93     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4      ┆ 127068927 ┆ 350  ┆ 37     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...    ┆ ...       ┆ ...  ┆ ...    ┆ ... ┆ ...           ┆ ...      ┆ ...    ┆ ...           │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 163817 ┆ 2581628   ┆ 732  ┆ 190    ┆ ... ┆ 1             ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 163818 ┆ 96685857  ┆ 641  ┆ 53     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 163819 ┆ 157842933 ┆ 624  ┆ 8      ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ $null$        │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 163820 ┆ 17487527  ┆ 623  ┆ 82     ┆ ... ┆ $null$        ┆ $null$   ┆ $null$ ┆ 1             │
└────────┴───────────┴──────┴────────┴─────┴───────────────┴──────────┴────────┴───────────────┘

In [71]:
%%time
(df["NO"].cast(str).str.contains(r"^\d+$").sum(), df["CO_ID"].cast(str).str.contains(r"^\d+$").sum())

Wall time: 19.2 ms

(163820, 163820)

In [5]:
%%time
# df =op.load.file("data/crime.csv")
df =op.load.file("../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet")

Wall time: 2.22 s

In [28]:
df["NO"].mask.int()

      NO
  (bool)
--------
       1
       1
       1
       1
       1
       1
       1
       1
       1
       1
       1

In [36]:
for col_name in df.cols.names():    
    print(col_name)
    %prun df.cols.profile(col_name)

NO
Wall time: 1.43 s
CO_ID
Wall time: 1.63 s
ARPU
Wall time: 1.51 s
TENURE
Wall time: 1.61 s
FECHA_INST_TELEFONO
Wall time: 1.68 s
FECHA_INSTALACION
Wall time: 1.58 s
STATUS_TELEFONO
Wall time: 1.66 s
CANAL_VENTA
Wall time: 1.71 s
SUB_CANAL_VENTA
Wall time: 2.37 s
ID_VENDEDOR
Wall time: 1.87 s
ID_PLAN
Wall time: 2.15 s
PLAN_PREPAGO
Wall time: 1.84 s
ID_PLAN_ANTERIOR
Wall time: 1.67 s
FECHA_CAMBIO_PLAN
Wall time: 1.71 s
TRA_IN_LOC_Mean_6_MESES
Wall time: 1.74 s
TRA_IN_INT_Mean_6_MESES
Wall time: 1.67 s
TRA_IN_NAT_Mean_6_MESES
Wall time: 1.69 s
TRA_IN_MOBILE_Mean_6_MESES
Wall time: 2.19 s
TRA_IN_MOBILE_OTHER_Mean_6_MESES
Wall time: 1.66 s
TRA_OUT_LOC_Mean_6_MESES
Wall time: 1.56 s
TRA_OUT_INT_Mean_6_MESES
Wall time: 1.54 s
TRA_OUT_NAT_Mean_6_MESES
Wall time: 1.56 s
TRA_OUT_MOBILE_Mean_6_MESES
Wall time: 1.51 s
TRA_OUT_MOBILE_OTHER_Mean_6_MESES
Wall time: 1.57 s
SMS_OUT_AMT_Mean_6_MESES
Wall time: 1.74 s
RECHARGE_AMT_Mean_6_MESES
Wall time: 1.98 s
AMT_RENT_Mean_6_MESES

KeyboardInterrupt:

AMT_MIN_OUT_INT_Mean_6_MESES
Wall time: 1.88 s
AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES
Wall time: 1.82 s
AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES
Wall time: 1.7 s
AMT_MIN_OUT_MOBILE_Mean_6_MESES
Wall time: 1.63 s
AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES
Wall time: 1.68 s
AMT_ROAMING_SMS_Mean_6_MESES
Wall time: 1.65 s
AMT_ROAMING_DATA_Mean_6_MESES
Wall time: 1.79 s
AMT_ROAMING_VOICE_Mean_6_MESES
Wall time: 1.63 s
AMT_PAQUETICO_VOZ_Mean_6_MESES
Wall time: 1.63 s
AMT_PAQUETICO_DATA_Mean_6_MESES
Wall time: 1.65 s
AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES
Wall time: 1.8 s
MB_Mean_6_MESES
Wall time: 1.85 s
TRA_IN_LOC_Mean_3_MESES
Wall time: 1.71 s
TRA_IN_INT_Mean_3_MESES
Wall time: 1.65 s
TRA_IN_NAT_Mean_3_MESES
Wall time: 1.54 s
TRA_IN_MOBILE_Mean_3_MESES
Wall time: 1.54 s
TRA_IN_MOBILE_OTHER_Mean_3_MESES
Wall time: 1.64 s
TRA_OUT_LOC_Mean_3_MESES
Wall time: 1.66 s
TRA_OUT_INT_Mean_3_MESES
Wall time: 1.57 s
TRA_OUT_NAT_Mean_3_MESES
Wall time: 1.71 s
TRA_OUT_MOBILE_Mean_3_MESES
Wall time: 2.42 s
TRA_OUT_MOBILE_OTHER_Mean_3_MESES
Wall time: 2.33 s
SMS_OUT_AMT_Mean_3_MESES
Wall time: 1.93 s
RECHARGE_AMT_Mean_3_MESES
Wall time: 1.6 s
AMT_RENT_Mean_3_MESES
Wall time: 1.59 s
AMT_MIN_OUT_INT_Mean_3_MESES
Wall time: 1.56 s
AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES
Wall time: 1.63 s
AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES
Wall time: 1.65 s
AMT_MIN_OUT_MOBILE_Mean_3_MESES
Wall time: 1.82 s
AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES
Wall time: 1.68 s
AMT_ROAMING_SMS_Mean_3_MESES
Wall time: 1.67 s
AMT_ROAMING_DATA_Mean_3_MESES
Wall time: 1.56 s
AMT_ROAMING_VOICE_Mean_3_MESES
Wall time: 1.55 s
AMT_PAQUETICO_VOZ_Mean_3_MESES
Wall time: 1.55 s
AMT_PAQUETICO_DATA_Mean_3_MESES
Wall time: 1.69 s
AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES
Wall time: 1.73 s
MB_Mean_3_MESES
Wall time: 1.56 s
FECHA_NACIMIENTO
Wall time: 1.69 s
SEXO
Wall time: 1.93 s
SEGMENTO_BI
Wall time: 1.84 s
DESCRIPCION_PROVINCIA_CUENTA
Wall time: 1.67 s
DESCRIPCION_PROVINCIA_CVOZ
Wall time: 2.02 s
DESCRIPCION_PROVINCIA_CDATA
Wall time: 1.61 s
PROVINCIA
Wall time: 1.58 s
MONTO_RECARGA_Sum_MES_ANTERIOR
Wall time: 1.65 s
CANT_RECARGAS_MES_ANTERIOR
Wall time: 1.6 s
CABLE
Wall time: 1.6 s
TELEFONO_FIJO
Wall time: 1.77 s
INTERNET
Wall time: 1.75 s
MBB
Wall time: 1.69 s
MOVIL_POSPAGO
Wall time: 1.71 s

In [49]:
col_name = "NO"
%prun df[col_name].cols.profile(col_name)

In [48]:
%prun df.data["NO"].astype(str).str.match(r"^\d+$").sum()

In [14]:
for col_name in df.cols.names():
    print(col_name)
    %prun df[col_name].cols.quality(col_name)

NO
 CO_ID
 ARPU
 TENURE
 FECHA_INST_TELEFONO
 FECHA_INSTALACION
 STATUS_TELEFONO
 CANAL_VENTA
 SUB_CANAL_VENTA
 ID_VENDEDOR
 ID_PLAN
 PLAN_PREPAGO
 ID_PLAN_ANTERIOR
 FECHA_CAMBIO_PLAN
 TRA_IN_LOC_Mean_6_MESES
 TRA_IN_INT_Mean_6_MESES
 TRA_IN_NAT_Mean_6_MESES
 TRA_IN_MOBILE_Mean_6_MESES
 TRA_IN_MOBILE_OTHER_Mean_6_MESES
 TRA_OUT_LOC_Mean_6_MESES
 TRA_OUT_INT_Mean_6_MESES

KeyboardInterrupt:

In [18]:
df.cols.count_uniques()

AttributeError: 'int' object has no attribute 'astype'

In [ ]:
%prun df.cols.profile()

In [78]:
df.save.parquet("../../Data input/Base Pre2Pos para Modelo - Abr 22.parquet")

In [49]:
dfv = df.data

In [52]:
df.mask.null(col_name)

  MOVIL_POSPAGO
         (bool)
---------------
              0
              0
              0
              0
              0
              0
              0
              0
              0
              0
              0

In [10]:
df.cols.sum()

AttributeError: 'DataFrameLocal' object has no attribute 'count_uniques'

In [9]:
%%time
df.cols.profile(flush=True)

<class 'optimus.engines.pandas.dataframe.PandasDataFrame'>

AttributeError: 'DataFrame' object has no attribute 'count_uniques'

In [23]:
for col_name in df.cols.names():
    print(col_name)
    %time df[col_name].cols.quality(col_name)

NO
missing 0.0
Wall time: 86.9 ms
CO_ID
missing 0.0
Wall time: 104 ms
ARPU
missing 0.0
Wall time: 94.1 ms
TENURE
missing 0.0
Wall time: 91.6 ms
FECHA_INST_TELEFONO
missing 0.0
Wall time: 276 ms
FECHA_INSTALACION
missing 0.0
Wall time: 262 ms
STATUS_TELEFONO
missing 0.0
Wall time: 251 ms
CANAL_VENTA
missing 0.0
Wall time: 113 ms
SUB_CANAL_VENTA
missing 0.0
Wall time: 298 ms
ID_VENDEDOR
missing 0.0
Wall time: 317 ms
ID_PLAN
missing 0.0
Wall time: 265 ms
PLAN_PREPAGO
missing 0.0
Wall time: 234 ms
ID_PLAN_ANTERIOR
missing 0.0
Wall time: 260 ms
FECHA_CAMBIO_PLAN
missing 0.0
Wall time: 251 ms
TRA_IN_LOC_Mean_6_MESES
missing 0.0
Wall time: 99.8 ms
TRA_IN_INT_Mean_6_MESES
missing 0.0
Wall time: 95.6 ms
TRA_IN_NAT_Mean_6_MESES
missing 0.0
Wall time: 111 ms
TRA_IN_MOBILE_Mean_6_MESES
missing 0.0
Wall time: 112 ms
TRA_IN_MOBILE_OTHER_Mean_6_MESES
missing 0.0
Wall time: 104 ms
TRA_OUT_LOC_Mean_6_MESES
missing 0.0
Wall time: 107 ms
TRA_OUT_INT_Mean_6_MESES
missing 0.0
Wall time: 126 ms
TRA_OUT_NAT_Mean_6_MESES
missing 0.0
Wall time: 113 ms
TRA_OUT_MOBILE_Mean_6_MESES
missing 0.0
Wall time: 109 ms
TRA_OUT_MOBILE_OTHER_Mean_6_MESES
missing 0.0
Wall time: 101 ms
SMS_OUT_AMT_Mean_6_MESES
missing 0.0
Wall time: 103 ms
RECHARGE_AMT_Mean_6_MESES
missing 0.0
Wall time: 115 ms
AMT_RENT_Mean_6_MESES
missing 0.0
Wall time: 105 ms
AMT_MIN_OUT_INT_Mean_6_MESES
missing 0.0
Wall time: 107 ms
AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES
missing 0.0
Wall time: 117 ms
AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES
missing 0.0
Wall time: 125 ms
AMT_MIN_OUT_MOBILE_Mean_6_MESES
missing 0.0
Wall time: 114 ms
AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES
missing 0.0
Wall time: 110 ms
AMT_ROAMING_SMS_Mean_6_MESES
missing 0.0
Wall time: 104 ms
AMT_ROAMING_DATA_Mean_6_MESES
missing 0.0
Wall time: 107 ms
AMT_ROAMING_VOICE_Mean_6_MESES
missing 0.0
Wall time: 123 ms
AMT_PAQUETICO_VOZ_Mean_6_MESES
missing 0.0
Wall time: 116 ms
AMT_PAQUETICO_DATA_Mean_6_MESES
missing 0.0
Wall time: 131 ms
AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES
missing 0.0
Wall time: 131 ms
MB_Mean_6_MESES
missing 0.0
Wall time: 127 ms
TRA_IN_LOC_Mean_3_MESES
missing 0.0
Wall time: 133 ms
TRA_IN_INT_Mean_3_MESES
missing 0.0
Wall time: 119 ms
TRA_IN_NAT_Mean_3_MESES
missing 0.0
Wall time: 171 ms
TRA_IN_MOBILE_Mean_3_MESES
missing 0.0
Wall time: 143 ms
TRA_IN_MOBILE_OTHER_Mean_3_MESES
missing 0.0
Wall time: 138 ms
TRA_OUT_LOC_Mean_3_MESES
missing 0.0
Wall time: 126 ms
TRA_OUT_INT_Mean_3_MESES
missing 0.0
Wall time: 129 ms
TRA_OUT_NAT_Mean_3_MESES
missing 0.0
Wall time: 132 ms
TRA_OUT_MOBILE_Mean_3_MESES
missing 0.0
Wall time: 136 ms
TRA_OUT_MOBILE_OTHER_Mean_3_MESES
missing 0.0
Wall time: 132 ms
SMS_OUT_AMT_Mean_3_MESES
missing 0.0
Wall time: 142 ms
RECHARGE_AMT_Mean_3_MESES
missing 0.0
Wall time: 111 ms
AMT_RENT_Mean_3_MESES
missing 0.0
Wall time: 114 ms
AMT_MIN_OUT_INT_Mean_3_MESES
missing 0.0
Wall time: 111 ms
AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES
missing 0.0
Wall time: 107 ms
AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES
missing 0.0
Wall time: 102 ms
AMT_MIN_OUT_MOBILE_Mean_3_MESES
missing 0.0
Wall time: 101 ms
AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES
missing 0.0
Wall time: 107 ms
AMT_ROAMING_SMS_Mean_3_MESES
missing 0.0
Wall time: 99.9 ms
AMT_ROAMING_DATA_Mean_3_MESES
missing 0.0
Wall time: 116 ms
AMT_ROAMING_VOICE_Mean_3_MESES
missing 0.0
Wall time: 108 ms
AMT_PAQUETICO_VOZ_Mean_3_MESES
missing 0.0
Wall time: 100 ms
AMT_PAQUETICO_DATA_Mean_3_MESES
missing 0.0
Wall time: 107 ms
AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES
missing 0.0
Wall time: 111 ms
MB_Mean_3_MESES
missing 0.0
Wall time: 119 ms
FECHA_NACIMIENTO
missing 0.0
Wall time: 331 ms
SEXO
missing 0.0
Wall time: 302 ms
SEGMENTO_BI
missing 0.0
Wall time: 290 ms
DESCRIPCION_PROVINCIA_CUENTA
missing 0.0
Wall time: 351 ms
DESCRIPCION_PROVINCIA_CVOZ
missing 0.0
Wall time: 320 ms
DESCRIPCION_PROVINCIA_CDATA
missing 0.0
Wall time: 268 ms
PROVINCIA
missing 0.0
Wall time: 276 ms
MONTO_RECARGA_Sum_MES_ANTERIOR
missing 0.0
Wall time: 257 ms
CANT_RECARGAS_MES_ANTERIOR
missing 0.0
Wall time: 268 ms
CABLE
missing 0.0
Wall time: 278 ms
TELEFONO_FIJO
missing 0.0
Wall time: 282 ms
INTERNET
missing 0.0
Wall time: 322 ms
MBB
missing 0.0
Wall time: 344 ms
MOVIL_POSPAGO
missing 0.0
Wall time: 308 ms

In [39]:
df.mask.null("NO")

NO            CO_ID       ARPU     TENURE  FECHA_INST_TELEFONO    FECHA_INSTALACION    STATUS_TELEFONO      CANAL_VENTA    SUB_CANAL_VENTA  ID_VENDEDOR    ID_PLAN     PLAN_PREPAGO    ID_PLAN_ANTERIOR    FECHA_CAMBIO_PLAN      TRA_IN_LOC_Mean_6_MESES    TRA_IN_INT_Mean_6_MESES    TRA_IN_NAT_Mean_6_MESES    TRA_IN_MOBILE_Mean_6_MESES    TRA_IN_MOBILE_OTHER_Mean_6_MESES    TRA_OUT_LOC_Mean_6_MESES    TRA_OUT_INT_Mean_6_MESES    TRA_OUT_NAT_Mean_6_MESES    TRA_OUT_MOBILE_Mean_6_MESES    TRA_OUT_MOBILE_OTHER_Mean_6_MESES    SMS_OUT_AMT_Mean_6_MESES    RECHARGE_AMT_Mean_6_MESES    AMT_RENT_Mean_6_MESES    AMT_MIN_OUT_INT_Mean_6_MESES    AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES    AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES    AMT_MIN_OUT_MOBILE_Mean_6_MESES    AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES    AMT_ROAMING_SMS_Mean_6_MESES    AMT_ROAMING_DATA_Mean_6_MESES    AMT_ROAMING_VOICE_Mean_6_MESES    AMT_PAQUETICO_VOZ_Mean_6_MESES    AMT_PAQUETICO_DATA_Mean_6_MESES    AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES    MB_Mean_6_MESES    TRA_IN_LOC_Mean_3_MESES    TRA_IN_INT_Mean_3_MESES    TRA_IN_NAT_Mean_3_MESES    TRA_IN_MOBILE_Mean_3_MESES    TRA_IN_MOBILE_OTHER_Mean_3_MESES    TRA_OUT_LOC_Mean_3_MESES    TRA_OUT_INT_Mean_3_MESES    TRA_OUT_NAT_Mean_3_MESES    TRA_OUT_MOBILE_Mean_3_MESES    TRA_OUT_MOBILE_OTHER_Mean_3_MESES    SMS_OUT_AMT_Mean_3_MESES    RECHARGE_AMT_Mean_3_MESES    AMT_RENT_Mean_3_MESES    AMT_MIN_OUT_INT_Mean_3_MESES    AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES    AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES    AMT_MIN_OUT_MOBILE_Mean_3_MESES    AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES    AMT_ROAMING_SMS_Mean_3_MESES    AMT_ROAMING_DATA_Mean_3_MESES    AMT_ROAMING_VOICE_Mean_3_MESES    AMT_PAQUETICO_VOZ_Mean_3_MESES    AMT_PAQUETICO_DATA_Mean_3_MESES    AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES    MB_Mean_3_MESES  FECHA_NACIMIENTO     SEXO        SEGMENTO_BI    DESCRIPCION_PROVINCIA_CUENTA    DESCRIPCION_PROVINCIA_CVOZ    DESCRIPCION_PROVINCIA_CDATA    PROVINCIA             MONTO_RECARGA_Sum_MES_ANTERIOR    CANT_RECARGAS_MES_ANTERIOR    CABLE       TELEFONO_FIJO    INTERNET    MBB         MOVIL_POSPAGO
(bool)      (int64)    (int64)    (int64)  (string)               (string)             (string)                 (int64)           (string)  (string)       (string)    (string)        (string)            (string)                             (float64)                  (float64)                  (float64)                     (float64)                           (float64)                   (float64)                   (float64)                   (float64)                      (float64)                            (float64)                   (float64)                    (float64)                (float64)                       (float64)                                (float64)                               (float64)                          (float64)                                     (float64)                       (float64)                        (float64)                         (float64)                         (float64)                          (float64)                              (float64)          (float64)                  (float64)                  (float64)                  (float64)                     (float64)                           (float64)                   (float64)                   (float64)                   (float64)                      (float64)                            (float64)                   (float64)                    (float64)                (float64)                       (float64)                                (float64)                               (float64)                          (float64)                                     (float64)                       (float64)                        (float64)                         (float64)                         (float64)                          (float64)                              (float64)          (float64)  (string)             (string)    (string)       (string)                        (string)                      (string)                       (string)              (string)                          (string)                      (string)    (string)         (string)    (string)    (string)
--------  ---------  ---------  ---------  ---------------------  -------------------  -----------------  -------------  -----------------  -------------  ----------  --------------  ------------------  -------------------  -------------------------  -------------------------  -------------------------  ----------------------------  ----------------------------------  --------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------------  --------------------------  ---------------------------  -----------------------  ------------------------------  ---------------------------------------  --------------------------------------  ---------------------------------  --------------------------------------------  ------------------------------  -------------------------------  --------------------------------  --------------------------------  ---------------------------------  -------------------------------------  -----------------  -------------------------  -------------------------  -------------------------  ----------------------------  ----------------------------------  --------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------------  --------------------------  ---------------------------  -----------------------  ------------------------------  ---------------------------------------  --------------------------------------  ---------------------------------  --------------------------------------------  ------------------------------  -------------------------------  --------------------------------  --------------------------------  ---------------------------------  -------------------------------------  -----------------  -------------------  ----------  -------------  ------------------------------  ----------------------------  -----------------------------  --------------------  --------------------------------  ----------------------------  ----------  ---------------  ----------  ----------  ---------------
False      12881892        384        109  2013-01-30 00:00:00    2013-01-30 00:00:00  A                              6               4601  18425          CEPREVO005  S               $null$              $null$                                   1.55                       0.986                      2.384                        17.903                              35.277                       4.271                       0                           2.16                           6.134                                7.396                       3.143                      340.651                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0.014                      1.763                      1.32                       3.703                        17.527                              39.467                       2.58                        0                            0.76                          8                                    5.837                       5.333                      282.047                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0.011  1982-04-12 00:00:00  M           E              SAN PEDRO DE MACORIS            SAN PEDRO DE MACORIS          $null$                         SAN PEDRO DE MACORIS  76.920                            1                             1           $null$           $null$      $null$      $null$
False     136449998        410         32  2019-07-19 00:00:00    2022-02-06 00:00:00  A                              3               2903  24425          CEPREVO004  S               $null$              $null$                                   3.323                      0                          0                           126.01                                5.379                       0.007                       0                           0                             18.44                                 1.474                       4                          393.626                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           3505.54                       2.173                      0                          0                           128.703                               4.597                       0.017                       0                            0                             0.753                                0.1                         5.333                      197.433                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           2940.91   1995-05-10 00:00:00  F           $null$         DUARTE                          DUARTE                        $null$                         DUARTE                $null$                            $null$                        $null$      $null$           $null$      1           $null$
False      15661796        654         93  2014-06-20 00:00:00    2014-06-20 00:00:00  A                              6                358  19394          CEPREVO005  S               $null$              $null$                                   0.124                      0                          0                           110.039                              87.179                       0.549                       0                           0                              9.119                                5.939                      16.143                      515.26                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          20121.6                        0.29                       0                          0                           112.61                               19.15                        0                           0                            0                            12.01                                 9.71                       14.333                      575.98                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          23524.5    1993-02-15 00:00:00  F           E              DISTRITO NACIONAL               SAN JUAN                      $null$                         SAN JUAN              804.880                           8                             $null$      $null$           $null$      $null$      $null$
False     127068927        350         37  2019-01-29 00:00:00    2019-01-31 00:00:00  A                              3               1919  23502          CEPREVO005  S               $null$              $null$                                   0.566                      0                          0                             3.311                               3.483                       0                           0                           0                              0.069                                0.471                       0                          212.297                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           1296.56                       0                          0                          0                             0.493                               5.147                       0                           0                            0                             0.16                                 1.1                         0                           38.46                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              1.238  1973-09-30 00:00:00  F           E              AZUA                            SANTIAGO                      $null$                         SANTIAGO              115.380                           2                             $null$      $null$           $null$      $null$      $null$
False     156732494        660          9  2021-06-14 00:00:00    2021-06-14 00:00:00  A                              6              11361  E6314          CEPREVO005  S               $null$              $null$                                   0.049                      0                          0                             1.137                              10.38                        0.263                       0                           0                              1.071                                4.966                       2                          348.34                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          11663.5                        0                          0                          0                             0.653                               0.433                       0.613                       0                            0                             1.12                                 2.133                       2.667                      307.68                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          11349.3    1997-07-30 00:00:00  F           E              DISTRITO NACIONAL               SANTO DOMINGO                 $null$                         SANTO DOMINGO         $null$                            $null$                        $null$      $null$           $null$      $null$      $null$
False     158282264        741          7  2021-07-30 00:00:00    2021-07-30 00:00:00  A                              3               5598  25430          CEPREVO005  S               $null$              $null$                                   0                          0                          0                             0.3                                 3.246                       0                           0                           0                              1.094                                5.943                       1.857                       63.954                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0            164.832                      0                          0                          0                             0                                   0.713                       0                           0                            0                             0                                    0                           2.333                        0                            0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0      1990-12-24 00:00:00  M           E              BAHORUCO                        $null$                        $null$                         BAHORUCO              $null$                            $null$                        $null$      $null$           $null$      $null$      $null$

In [26]:
df.data["CO_ID"] ="1"

In [27]:
dfv = df.data["CO_ID"]
dfv
def func(value):
    return value

dfv = df.data.apply(func, dfv)

In [28]:
df.data

TypeError: 'int' object is not subscriptable

TypeError: 'int' object is not subscriptable

TypeError: 'int' object is not subscriptable

In [ ]:
import vaex
with vaex.progress.tree('rich', title="Two passes"):
    df.cols.sum("*")

Output()

In [6]:
df

limit 10

       NO      CO_ID       ARPU     TENURE  FECHA_INST_TELEFONO    FECHA_INSTALACION    STATUS_TELEFONO      CANAL_VENTA    SUB_CANAL_VENTA  ID_VENDEDOR    ID_PLAN     PLAN_PREPAGO    ID_PLAN_ANTERIOR    FECHA_CAMBIO_PLAN      TRA_IN_LOC_Mean_6_MESES    TRA_IN_INT_Mean_6_MESES    TRA_IN_NAT_Mean_6_MESES    TRA_IN_MOBILE_Mean_6_MESES    TRA_IN_MOBILE_OTHER_Mean_6_MESES    TRA_OUT_LOC_Mean_6_MESES    TRA_OUT_INT_Mean_6_MESES    TRA_OUT_NAT_Mean_6_MESES    TRA_OUT_MOBILE_Mean_6_MESES    TRA_OUT_MOBILE_OTHER_Mean_6_MESES    SMS_OUT_AMT_Mean_6_MESES    RECHARGE_AMT_Mean_6_MESES    AMT_RENT_Mean_6_MESES    AMT_MIN_OUT_INT_Mean_6_MESES    AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES    AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES    AMT_MIN_OUT_MOBILE_Mean_6_MESES    AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES    AMT_ROAMING_SMS_Mean_6_MESES    AMT_ROAMING_DATA_Mean_6_MESES    AMT_ROAMING_VOICE_Mean_6_MESES    AMT_PAQUETICO_VOZ_Mean_6_MESES    AMT_PAQUETICO_DATA_Mean_6_MESES    AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES    MB_Mean_6_MESES    TRA_IN_LOC_Mean_3_MESES    TRA_IN_INT_Mean_3_MESES    TRA_IN_NAT_Mean_3_MESES    TRA_IN_MOBILE_Mean_3_MESES    TRA_IN_MOBILE_OTHER_Mean_3_MESES    TRA_OUT_LOC_Mean_3_MESES    TRA_OUT_INT_Mean_3_MESES    TRA_OUT_NAT_Mean_3_MESES    TRA_OUT_MOBILE_Mean_3_MESES    TRA_OUT_MOBILE_OTHER_Mean_3_MESES    SMS_OUT_AMT_Mean_3_MESES    RECHARGE_AMT_Mean_3_MESES    AMT_RENT_Mean_3_MESES    AMT_MIN_OUT_INT_Mean_3_MESES    AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES    AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES    AMT_MIN_OUT_MOBILE_Mean_3_MESES    AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES    AMT_ROAMING_SMS_Mean_3_MESES    AMT_ROAMING_DATA_Mean_3_MESES    AMT_ROAMING_VOICE_Mean_3_MESES    AMT_PAQUETICO_VOZ_Mean_3_MESES    AMT_PAQUETICO_DATA_Mean_3_MESES    AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES    MB_Mean_3_MESES  FECHA_NACIMIENTO     SEXO        SEGMENTO_BI    DESCRIPCION_PROVINCIA_CUENTA    DESCRIPCION_PROVINCIA_CVOZ    DESCRIPCION_PROVINCIA_CDATA    PROVINCIA             MONTO_RECARGA_Sum_MES_ANTERIOR    CANT_RECARGAS_MES_ANTERIOR    CABLE       TELEFONO_FIJO    INTERNET    MBB         MOVIL_POSPAGO
  (int64)    (int64)    (int64)    (int64)  (string)               (string)             (string)                 (int64)           (string)  (string)       (string)    (string)        (string)            (string)                             (float64)                  (float64)                  (float64)                     (float64)                           (float64)                   (float64)                   (float64)                   (float64)                      (float64)                            (float64)                   (float64)                    (float64)                (float64)                       (float64)                                (float64)                               (float64)                          (float64)                                     (float64)                       (float64)                        (float64)                         (float64)                         (float64)                          (float64)                              (float64)          (float64)                  (float64)                  (float64)                  (float64)                     (float64)                           (float64)                   (float64)                   (float64)                   (float64)                      (float64)                            (float64)                   (float64)                    (float64)                (float64)                       (float64)                                (float64)                               (float64)                          (float64)                                     (float64)                       (float64)                        (float64)                         (float64)                         (float64)                          (float64)                              (float64)          (float64)  (string)             (string)    (string)       (string)                        (string)                      (string)                       (string)              (string)                          (string)                      (string)    (string)         (string)    (string)    (string)
---------  ---------  ---------  ---------  ---------------------  -------------------  -----------------  -------------  -----------------  -------------  ----------  --------------  ------------------  -------------------  -------------------------  -------------------------  -------------------------  ----------------------------  ----------------------------------  --------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------------  --------------------------  ---------------------------  -----------------------  ------------------------------  ---------------------------------------  --------------------------------------  ---------------------------------  --------------------------------------------  ------------------------------  -------------------------------  --------------------------------  --------------------------------  ---------------------------------  -------------------------------------  -----------------  -------------------------  -------------------------  -------------------------  ----------------------------  ----------------------------------  --------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------------  --------------------------  ---------------------------  -----------------------  ------------------------------  ---------------------------------------  --------------------------------------  ---------------------------------  --------------------------------------------  ------------------------------  -------------------------------  --------------------------------  --------------------------------  ---------------------------------  -------------------------------------  -----------------  -------------------  ----------  -------------  ------------------------------  ----------------------------  -----------------------------  --------------------  --------------------------------  ----------------------------  ----------  ---------------  ----------  ----------  ---------------
        1   12881892        384        109  2013-01-30 00:00:00    2013-01-30 00:00:00  A                              6               4601  18425          CEPREVO005  S               $null$              $null$                                   1.55                       0.986                      2.384                        17.903                              35.277                       4.271                       0                           2.16                           6.134                                7.396                       3.143                      340.651                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0.014                      1.763                      1.32                       3.703                        17.527                              39.467                       2.58                        0                            0.76                          8                                    5.837                       5.333                      282.047                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0.011  1982-04-12 00:00:00  M           E              SAN PEDRO DE MACORIS            SAN PEDRO DE MACORIS          $null$                         SAN PEDRO DE MACORIS  76.920                            1                             1           $null$           $null$      $null$      $null$
        2  136449998        410         32  2019-07-19 00:00:00    2022-02-06 00:00:00  A                              3               2903  24425          CEPREVO004  S               $null$              $null$                                   3.323                      0                          0                           126.01                                5.379                       0.007                       0                           0                             18.44                                 1.474                       4                          393.626                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           3505.54                       2.173                      0                          0                           128.703                               4.597                       0.017                       0                            0                             0.753                                0.1                         5.333                      197.433                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           2940.91   1995-05-10 00:00:00  F           $null$         DUARTE                          DUARTE                        $null$                         DUARTE                $null$                            $null$                        $null$      $null$           $null$      1           $null$
        3   15661796        654         93  2014-06-20 00:00:00    2014-06-20 00:00:00  A                              6                358  19394          CEPREVO005  S               $null$              $null$                                   0.124                      0                          0                           110.039                              87.179                       0.549                       0                           0                              9.119                                5.939                      16.143                      515.26                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          20121.6                        0.29                       0                          0                           112.61                               19.15                        0                           0                            0                            12.01                                 9.71                       14.333                      575.98                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          23524.5    1993-02-15 00:00:00  F           E              DISTRITO NACIONAL               SAN JUAN                      $null$                         SAN JUAN              804.880                           8                             $null$      $null$           $null$      $null$      $null$
        4  127068927        350         37  2019-01-29 00:00:00    2019-01-31 00:00:00  A                              3               1919  23502          CEPREVO005  S               $null$              $null$                                   0.566                      0                          0                             3.311                               3.483                       0                           0                           0                              0.069                                0.471                       0                          212.297                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           1296.56                       0                          0                          0                             0.493                               5.147                       0                           0                            0                             0.16                                 1.1                         0                           38.46                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              1.238  1973-09-30 00:00:00  F           E              AZUA                            SANTIAGO                      $null$                         SANTIAGO              115.380                           2                             $null$      $null$           $null$      $null$      $null$
        5  156732494        660          9  2021-06-14 00:00:00    2021-06-14 00:00:00  A                              6              11361  E6314          CEPREVO005  S               $null$              $null$                                   0.049                      0                          0                             1.137                              10.38                        0.263                       0                           0                              1.071                                4.966                       2                          348.34                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          11663.5                        0                          0                          0                             0.653                               0.433                       0.613                       0                            0                             1.12                                 2.133                       2.667                      307.68                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          11349.3    1997-07-30 00:00:00  F           E              DISTRITO NACIONAL               SANTO DOMINGO                 $null$                         SANTO DOMINGO         $null$                            $null$                        $null$      $null$           $null$      $null$      $null$
        6  158282264        741          7  2021-07-30 00:00:00    2021-07-30 00:00:00  A                              3               5598  25430          CEPREVO005  S               $null$              $null$                                   0                          0                          0                             0.3                                 3.246                       0                           0                           0                              1.094                                5.943                       1.857                       63.954                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0            164.832                      0                          0                          0                             0                                   0.713                       0                           0                            0                             0                                    0                           2.333                        0                            0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0      1990-12-24 00:00:00  M           E              BAHORUCO                        $null$                        $null$                         BAHORUCO              $null$                            $null$                        $null$      $null$           $null$      $null$      $null$

In [12]:
%%time
df

Wall time: 0 ns
limit 10

       NO      CO_ID       ARPU     TENURE  FECHA_INST_TELEFONO    FECHA_INSTALACION    STATUS_TELEFONO      CANAL_VENTA    SUB_CANAL_VENTA  ID_VENDEDOR    ID_PLAN     PLAN_PREPAGO    ID_PLAN_ANTERIOR    FECHA_CAMBIO_PLAN      TRA_IN_LOC_Mean_6_MESES    TRA_IN_INT_Mean_6_MESES    TRA_IN_NAT_Mean_6_MESES    TRA_IN_MOBILE_Mean_6_MESES    TRA_IN_MOBILE_OTHER_Mean_6_MESES    TRA_OUT_LOC_Mean_6_MESES    TRA_OUT_INT_Mean_6_MESES    TRA_OUT_NAT_Mean_6_MESES    TRA_OUT_MOBILE_Mean_6_MESES    TRA_OUT_MOBILE_OTHER_Mean_6_MESES    SMS_OUT_AMT_Mean_6_MESES    RECHARGE_AMT_Mean_6_MESES    AMT_RENT_Mean_6_MESES    AMT_MIN_OUT_INT_Mean_6_MESES    AMT_MIN_OUT_MOBILE_OTHER_Mean_6_MESES    AMT_MIN_OUT_OFF_NET_FIX_Mean_6_MESES    AMT_MIN_OUT_MOBILE_Mean_6_MESES    AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_6_MESES    AMT_ROAMING_SMS_Mean_6_MESES    AMT_ROAMING_DATA_Mean_6_MESES    AMT_ROAMING_VOICE_Mean_6_MESES    AMT_PAQUETICO_VOZ_Mean_6_MESES    AMT_PAQUETICO_DATA_Mean_6_MESES    AMT_MIN_OUT_ON_NET_FIX_Mean_6_MESES    MB_Mean_6_MESES    TRA_IN_LOC_Mean_3_MESES    TRA_IN_INT_Mean_3_MESES    TRA_IN_NAT_Mean_3_MESES    TRA_IN_MOBILE_Mean_3_MESES    TRA_IN_MOBILE_OTHER_Mean_3_MESES    TRA_OUT_LOC_Mean_3_MESES    TRA_OUT_INT_Mean_3_MESES    TRA_OUT_NAT_Mean_3_MESES    TRA_OUT_MOBILE_Mean_3_MESES    TRA_OUT_MOBILE_OTHER_Mean_3_MESES    SMS_OUT_AMT_Mean_3_MESES    RECHARGE_AMT_Mean_3_MESES    AMT_RENT_Mean_3_MESES    AMT_MIN_OUT_INT_Mean_3_MESES    AMT_MIN_OUT_MOBILE_OTHER_Mean_3_MESES    AMT_MIN_OUT_OFF_NET_FIX_Mean_3_MESES    AMT_MIN_OUT_MOBILE_Mean_3_MESES    AMT_MIN_OUT_MOBILE_SPE_TARIFF_Mean_3_MESES    AMT_ROAMING_SMS_Mean_3_MESES    AMT_ROAMING_DATA_Mean_3_MESES    AMT_ROAMING_VOICE_Mean_3_MESES    AMT_PAQUETICO_VOZ_Mean_3_MESES    AMT_PAQUETICO_DATA_Mean_3_MESES    AMT_MIN_OUT_ON_NET_FIX_Mean_3_MESES    MB_Mean_3_MESES  FECHA_NACIMIENTO     SEXO        SEGMENTO_BI    DESCRIPCION_PROVINCIA_CUENTA    DESCRIPCION_PROVINCIA_CVOZ    DESCRIPCION_PROVINCIA_CDATA    PROVINCIA             MONTO_RECARGA_Sum_MES_ANTERIOR    CANT_RECARGAS_MES_ANTERIOR    CABLE       TELEFONO_FIJO    INTERNET    MBB         MOVIL_POSPAGO
  (int64)    (int64)    (int64)    (int64)  (string)               (string)             (string)                 (int64)           (string)  (string)       (string)    (string)        (string)            (string)                             (float64)                  (float64)                  (float64)                     (float64)                           (float64)                   (float64)                   (float64)                   (float64)                      (float64)                            (float64)                   (float64)                    (float64)                (float64)                       (float64)                                (float64)                               (float64)                          (float64)                                     (float64)                       (float64)                        (float64)                         (float64)                         (float64)                          (float64)                              (float64)          (float64)                  (float64)                  (float64)                  (float64)                     (float64)                           (float64)                   (float64)                   (float64)                   (float64)                      (float64)                            (float64)                   (float64)                    (float64)                (float64)                       (float64)                                (float64)                               (float64)                          (float64)                                     (float64)                       (float64)                        (float64)                         (float64)                         (float64)                          (float64)                              (float64)          (float64)  (string)             (string)    (string)       (string)                        (string)                      (string)                       (string)              (string)                          (string)                      (string)    (string)         (string)    (string)    (string)
---------  ---------  ---------  ---------  ---------------------  -------------------  -----------------  -------------  -----------------  -------------  ----------  --------------  ------------------  -------------------  -------------------------  -------------------------  -------------------------  ----------------------------  ----------------------------------  --------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------------  --------------------------  ---------------------------  -----------------------  ------------------------------  ---------------------------------------  --------------------------------------  ---------------------------------  --------------------------------------------  ------------------------------  -------------------------------  --------------------------------  --------------------------------  ---------------------------------  -------------------------------------  -----------------  -------------------------  -------------------------  -------------------------  ----------------------------  ----------------------------------  --------------------------  --------------------------  --------------------------  -----------------------------  -----------------------------------  --------------------------  ---------------------------  -----------------------  ------------------------------  ---------------------------------------  --------------------------------------  ---------------------------------  --------------------------------------------  ------------------------------  -------------------------------  --------------------------------  --------------------------------  ---------------------------------  -------------------------------------  -----------------  -------------------  ----------  -------------  ------------------------------  ----------------------------  -----------------------------  --------------------  --------------------------------  ----------------------------  ----------  ---------------  ----------  ----------  ---------------
        1   12881892        384        109  2013-01-30 00:00:00    2013-01-30 00:00:00  A                              6               4601  18425          CEPREVO005  S               $null$              $null$                                   1.55                       0.986                      2.384                        17.903                              35.277                       4.271                       0                           2.16                           6.134                                7.396                       3.143                      340.651                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0.014                      1.763                      1.32                       3.703                        17.527                              39.467                       2.58                        0                            0.76                          8                                    5.837                       5.333                      282.047                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0.011  1982-04-12 00:00:00  M           E              SAN PEDRO DE MACORIS            SAN PEDRO DE MACORIS          $null$                         SAN PEDRO DE MACORIS  76.920                            1                             1           $null$           $null$      $null$      $null$
        2  136449998        410         32  2019-07-19 00:00:00    2022-02-06 00:00:00  A                              3               2903  24425          CEPREVO004  S               $null$              $null$                                   3.323                      0                          0                           126.01                                5.379                       0.007                       0                           0                             18.44                                 1.474                       4                          393.626                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           3505.54                       2.173                      0                          0                           128.703                               4.597                       0.017                       0                            0                             0.753                                0.1                         5.333                      197.433                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           2940.91   1995-05-10 00:00:00  F           $null$         DUARTE                          DUARTE                        $null$                         DUARTE                $null$                            $null$                        $null$      $null$           $null$      1           $null$
        3   15661796        654         93  2014-06-20 00:00:00    2014-06-20 00:00:00  A                              6                358  19394          CEPREVO005  S               $null$              $null$                                   0.124                      0                          0                           110.039                              87.179                       0.549                       0                           0                              9.119                                5.939                      16.143                      515.26                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          20121.6                        0.29                       0                          0                           112.61                               19.15                        0                           0                            0                            12.01                                 9.71                       14.333                      575.98                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          23524.5    1993-02-15 00:00:00  F           E              DISTRITO NACIONAL               SAN JUAN                      $null$                         SAN JUAN              804.880                           8                             $null$      $null$           $null$      $null$      $null$
        4  127068927        350         37  2019-01-29 00:00:00    2019-01-31 00:00:00  A                              3               1919  23502          CEPREVO005  S               $null$              $null$                                   0.566                      0                          0                             3.311                               3.483                       0                           0                           0                              0.069                                0.471                       0                          212.297                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0           1296.56                       0                          0                          0                             0.493                               5.147                       0                           0                            0                             0.16                                 1.1                         0                           38.46                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              1.238  1973-09-30 00:00:00  F           E              AZUA                            SANTIAGO                      $null$                         SANTIAGO              115.380                           2                             $null$      $null$           $null$      $null$      $null$
        5  156732494        660          9  2021-06-14 00:00:00    2021-06-14 00:00:00  A                              6              11361  E6314          CEPREVO005  S               $null$              $null$                                   0.049                      0                          0                             1.137                              10.38                        0.263                       0                           0                              1.071                                4.966                       2                          348.34                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          11663.5                        0                          0                          0                             0.653                               0.433                       0.613                       0                            0                             1.12                                 2.133                       2.667                      307.68                         0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0          11349.3    1997-07-30 00:00:00  F           E              DISTRITO NACIONAL               SANTO DOMINGO                 $null$                         SANTO DOMINGO         $null$                            $null$                        $null$      $null$           $null$      $null$      $null$
        6  158282264        741          7  2021-07-30 00:00:00    2021-07-30 00:00:00  A                              3               5598  25430          CEPREVO005  S               $null$              $null$                                   0                          0                          0                             0.3                                 3.246                       0                           0                           0                              1.094                                5.943                       1.857                       63.954                        0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0            164.832                      0                          0                          0                             0                                   0.713                       0                           0                            0                             0                                    0                           2.333                        0                            0                               0                                        0                                       0                                  0                                             0                               0                                0                                 0                                 0                                  0                                      0              0      1990-12-24 00:00:00  M           E              BAHORUCO                        $null$                        $null$                         BAHORUCO              $null$                            $null$                        $null$      $null$           $null$      $null$      $null$

In [62]:
%timeit df.data.sum(df.cols.names([0,1,2,3]))

21 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]:
%%time
import vaex
with vaex.progress.tree('rich', title="Two passes"):
    dff = df.cols.to_float()

Output()

Wall time: 603 ms

In [8]:
dfv = dff.data